name: new_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  blinking_text: ^1.0.4
  bluetooth_state: ^0.0.1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  # flutter_blue: ^0.8.0
  flutter_bluetooth_serial: ^0.4.0
  flutter_launcher_icons: ^0.14.1
  flutter_svg: ^2.0.14
  fluttertoast: ^8.2.8
  http: ^1.2.2
  permission_handler: ^11.3.1
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
